Repository neighborly/go-pghelpers, pull requests merged in 2019-06, with the labels that each got.

#2 Some small clean up for tests
  tests/integration/connect_test.go
  tests/unit/generate_address_test.go
Labels: Type: Enhancement

#3 Add Readme and Release Drafter
  .github/main.workflow
  .github/release-drafter.yml
  LICENSE.md
  README.md
Labels: Type: Documentation, Type: Tooling

#5 Refactored go-pghelpers from go-errors
  connect.go
  go.mod
  go.sum
Labels: Type: Enhancement

#4 Removing config, now in go-observability
  config.go
  connect.go
  go.mod
  go.sum
  tests/integration/connect_test.go
  tests/unit/generate_address_test.go
Labels: Type: Breaking Change
